#include "../src/verify.c"
#include "../src/build.c"
#include "../src/install.c"
#include "../src/remove.c"
#include "../src/update.c"
#include "../src/database.c"

#include "../src/utils/sha256.c"
#include "../src/utils/catpkg/cache.c"
#include "../src/utils/catpkg/path.c"
#include "../src/utils/catpkg/pkginfo.c"
#include "../src/utils/nftw.c"
#include "../src/utils/fs.c"
#include "../src/utils/allow.c"